Console.WriteLine("Ubatuba");
Console.WriteLine("Caraguatatuba");
Console.WriteLine("Ilhabela");
Console.WriteLine("São Sebastião");
Console.WriteLine("Bertioga");
Console.WriteLine("Guarujá");
Console.WriteLine("Guarujá");
Console.WriteLine("Santos");
Console.WriteLine("São Vicente");
Console.WriteLine("Praia Grande");
Console.WriteLine("Mongaguá");
Console.WriteLine("Itanhaém");
Console.WriteLine("Peruíbe");
Console.WriteLine("Iguape");
Console.WriteLine("Ilha Comprida");
Console.WriteLine("Cananéia");
